# Commented buildings are ones needing to be finished

external_building_directions_relative_to_landmarks = {
	'adams_center': 'Adams Center is the X-shaped dorm on the west side of the Walker-Adams mall, just south of Lindsey street. It\'s between Cate Center and Couch Cafeteria.',
	'adams_hall': 'Adams Hall is attached to the Price College of Business, to the east of the library.',
	'administration_building': 'The Administration / OCCE building is south of the dorms, on Asp Avenue. It\'s right next to the three-pointed forum building.',
	'andrew_m_coats_hall': 'The Law building, Andrew Coats Hall, is on the south side of campus, next to the Sam Noble Oklahoma Museum of Natural History. It\'s on Timberdell Road across the street from the parking lot for the forum building.',
	# 'anne_and_henry_zarrow_hall': '',
	'armory': 'The Army and Navy R. O. T. C. Armory is north of the stadium parking lot, and directly across from Price Hall.',
	'asp_avenue_parking_facility': 'The parking facility on Asp Avenue is attached to the stadium on Asp Avenue. You can reach it by turning north onto Asp Avenue from Lindsey, and then turning right.',
	'bizzell_memorial_library': 'Bizzell Memorial Library is located ',
	# 'boomer_outreach_building': '',
	'boyd_house': 'Walk past the food court and out the western exit. Make your way to the north oval and walk directly due north until you hit Boyd street. On the left side, across the street, is the Boyd House.',
	# 'brooks_street_transfer_station': '',
	'buchanan_hall': 'Walk past Crossroads and out the southern exit. The building directly due south of the Union is Buchanan Hall.',
	'burton_hall': 'Walk past Crossroads and out the southern exit. Turn right and walk directly due west until you hit Elm avenue. Cross the street, turn right and walk directly due north. Burton should be the first building on your left.',
	# 'campus_depot': '',
	'carnegie_building': 'Walk past Crossroads and out the southern exit. Turn right and walk directly due west until you turn right and walk towards the north oval. Carnegie will be the first building on your right.',
	'carpenter_hall': 'Walk towards the One University store. Before hitting it, turn right, and make your way out the eastern exit. Turn left and walk directly due north. You\'ll pass the union and the union parking garage. The next building after that will be Carpenter Hall.',
	'carson_engineering_center': 'Walk towards the One University store. Before hitting it, turn right, and make your way out the eastern exit. Turn left and walk directly due north, until you hit Boyd street. Once you hit Boyd street, cross Asp avenue and the Carson Engineering Center should be directly in front of you.',
	'cate_center': 'Walk past Crossroads and out the southern exit. Make your way to the south oval and keep walking directly due south, even past Lindsey street. The Cate Center should be between the first set of buildings you hit after crossing Lindsey, and between the street you cross to get to the three dorm towers.',
	'catlett_music_center': 'Walk past Crossroads and out the southern exit. Turn right and walk directly due west until you hit Elm avenue. Cross the street, turn right and walk directly due north. The Catlett Music Center will be the last building before you hit Boyd street.',
	'chemistry_building': 'Walk past Crossroads and out the southern exit. Turn right and walk directly due west until you turn right and walk towards the north oval. The Chemistry building should be the second building on your left.',
	'collings_hall': 'Walk past Crossroads and out the southern exit. Make your way to the south oval and keep walking directly due south. Collings Hall will be the fourth building on your right.',
	'collums_commissary': 'Walk past Crossroads and out the southern exit. Make your way to the south oval and keep walking directly due south until you reach Lindsey street. When you hit Lindsey Street, turn left and walk directly due east. Once you cross Jenkins avenue, the Collums Commissary will be the second building on your left.',
	'copeland_hall': 'Walk past Crossroads and out the southern exit. Make your way to the south oval and keep walking directly due south. Copeland Hall will be the fifth building on your right.',
	'couch_cafeteria': 'Walk past Crossroads and out the southern exit. Make your way to the south oval and keep walking directly due south, even past Lindsey street. Past the three dorms, you\'ll run into a circular shaped building. That will be the Couch Cafeteria.',
	# 'couch_center': '',
	# 'cross_center': '',
	# 'dale_hall': '',
	# 'dale_hall_tower': '',
	# 'devon_energy_hall': '',
	# 'dunham_residential_college': '',
	# 'ellison_hall': '',
	# 'elm_ave_parking_facility': '',
	# 'engineering_laboratory': '',
	# 'evans_hall': '',
	# 'exxon_mobile_lawrence_g_rawl_practice_facility': '',
	# 'facilities_management_complex': '',
	# 'farzaneh_hall': '',
	# 'fears_structural_engineering_lab': '',
	# 'felgar_hall': '',
	# 'fine_arts_center': '',
	# 'five_partners_place': '',
	# 'forum_building': '',
	# 'four_partners_place': '',
	# 'fred_jones_junior_memorial_art_center': '',
	# 'gaylord_hall': '',
	# 'the_gaylord_family_oklahoma_memorial_stadium': '',
	'george_lynn_cross_hall': 'Walk past Crossroads and out the southern exit. Make your way to the south oval and keep walking directly due south until you can make a left on the second building down.',
	# 'goddard_health_center': '',
	# 'gould_hall': '',
	# 'headington_hall': '',
	# 'headington_residential_college': '',
	# 'housing_offices': '',
	# 'human_resources': '',
	# 'jacobs_field': '',
	# 'jacobson_hall': '',
	# 'jenkins_avenue_parking_facility': '',
	# 'jimmie_austin_o_u_golf_course': '',
	'jim_thorpe_multi_cultural_center': 'Walk past Crossroads and out the southern exit. Make your way to the south oval and keep walking directly due south, even past Lindsey street. Past the three dorms, you\'ll eventually run into a 3 pointed star shaped building. The Jim Thorpe Multi-Cultural Center, also known as the Commons Restaurant, will be located on the north west side of the block.',
	# 'kaufman_hall': '',
	# 'kraettli_apartments': '',
	# 'lissa_and_cy_wagner_student_academic_services_center': '',
	# 'lloyd_noble_center': '',
	# 'l_dale_mitchell_baseball_park': '',
	# 'mccarter_hall': '',
	# 'michael_f_price_college_of_business': '',
	# 'monnet_hall': '',
	# 'mosier_indoor_athletic_facility': '',
	# 'national_weather_center': '',
	# 'newman_hall': '',
	# 'nielsen_hall': '',
	# 'norman_fire_department_number_3': '',
	# 'nuclear_engineering_laboratory': '',
	# 'observatory': '',
	# 'old_faculty_club': '',
	# 'one_partners_place': '',
	# 'o_u_police_department': '',
	# 'o_u_traditions_square_east': '',
	# 'o_u_traditions_square_west': '',
	# 'parking_services': '',
	# 'physical_sciences_center': '',
	# 'reynolds_performing_arts_center': '',
	# 'richards_hall': '',
	# 'robertson_hall': '',
	# 'rupel_j_jones_theatre': '',
	# 'sam_noble_oklahoma_museum_of_natural_history': '',
	# 'sarkeys_energy_center': '',
	# 'sarkeys_physical_fitness_center': '',
	# 'science_hall': '',
	# 'sells_swim_complex': '',
	# 'sooner_cottage_suites': '',
	# 'stephenson_life_sciences_research_center': '',
	# 'stephenson_research_and_technology_center': '',
	# 'sutton_hall': '',
	# 't_howard_mccasland_field_house': '',
	# 'theta_m_dempsey_transportation_operations_center': '',
	# 'three_partners_place': '',
	# 'two_partners_place': '',
	# 'university_book_exchange': '',
	# 'university_of_oklahoma_foundation': '',
	# 'viersen_gymnastics_center': '',
	# 'walker_tower': '',
	# 'whitehand_hall': ''
}

external_building_directions_from_the_union = {
	'adams_center': 'Walk past Crossroads and out the southern exit. Make your way to the south oval and keep walking directly due south, even past Lindsey street, until you come across three X shaped buildings. Adams Center is on the first floor of the right most building you\'ll see.',
	'adams_hall': 'Walk past Crossroads and out the southern exit. Make your way to the south oval and keep walking directly due south, even past Lindsey street, until you come across three X shaped buildings. Adams Hall is located on the second floor and above in the right most building.',
	'administration_building': 'Walk past Crossroads and out the southern exit. Make your way to the south oval and keep walking directly due south until you reach Lindsey street. When you hit Lindsey Street, turn left and walk directly due east until you hit Asp avenue. Then turn right and walk directly due south on Asp avenue until you pass Fourth street. The administration building will be on your right.',
	'andrew_m_coats_hall': 'Walk past Crossroads and out the southern exit. Make your way to the south oval and keep walking directly due south until you reach Lindsey street. When you hit Lindsey Street, turn left and walk directly due east until you hit Asp avenue. Then turn right and walk directly due south on Asp avenue until you reach Timberdell road. Turn right on Timberdell road and walk directly due west until you can take your first left. The Andrew M Coats hall should be located directly down that road.',
	# 'anne_and_henry_zarrow_hall': '',
	'armory': 'Walk past Crossroads and out the southern exit. Make your way to the south oval. Once you hit the south oval, turn left and walk directly due east towards the stadium. The armory will be on your right, just before you hit the stadium.',
	'asp_avenue_parking_facility': 'Walk past Crossroads and out the southern exit. Make your way to the south oval. Once you hit the south oval, turn left and walk directly due east towards the stadium. Before walking past the armory, turn right and walk directly due south until you hit Asp avenue. Keep walking directly south and on your left should be the Asp avenue parking facility.',
	'bizzell_memorial_library': 'Walk past Crossroads and out the southern exit. Make your way to the south oval. Once you hit the south oval, turn right and walk directly due west until you can make your first right. The Bizzell library is located right in front of the south oval.',
	# 'boomer_outreach_building': '',
	'boyd_house': 'Walk past the food court and out the western exit. Make your way to the north oval and walk directly due north until you hit Boyd street. On the left side, across the street, is the Boyd House.',
	# 'brooks_street_transfer_station': '',
	'buchanan_hall': 'Walk past Crossroads and out the southern exit. The building directly due south of the Union is Buchanan Hall.',
	'burton_hall': 'Walk past Crossroads and out the southern exit. Turn right and walk directly due west until you hit Elm avenue. Cross the street, turn right and walk directly due north. Burton should be the first building on your left.',
	# 'campus_depot': '',
	'carnegie_building': 'Walk past Crossroads and out the southern exit. Turn right and walk directly due west until you turn right and walk towards the north oval. Carnegie will be the first building on your right.',
	'carpenter_hall': 'Walk towards the One University store. Before hitting it, turn right, and make your way out the eastern exit. Turn left and walk directly due north. You\'ll pass the union and the union parking garage. The next building after that will be Carpenter Hall.',
	'carson_engineering_center': 'Walk towards the One University store. Before hitting it, turn right, and make your way out the eastern exit. Turn left and walk directly due north, until you hit Boyd street. Once you hit Boyd street, cross Asp avenue and the Carson Engineering Center should be directly in front of you.',
	'cate_center': 'Walk past Crossroads and out the southern exit. Make your way to the south oval and keep walking directly due south, even past Lindsey street. The Cate Center should be between the first set of buildings you hit after crossing Lindsey, and between the street you cross to get to the three dorm towers.',
	'catlett_music_center': 'Walk past Crossroads and out the southern exit. Turn right and walk directly due west until you hit Elm avenue. Cross the street, turn right and walk directly due north. The Catlett Music Center will be the last building before you hit Boyd street.',
	'chemistry_building': 'Walk past Crossroads and out the southern exit. Turn right and walk directly due west until you turn right and walk towards the north oval. The Chemistry building should be the second building on your left.',
	'collings_hall': 'Walk past Crossroads and out the southern exit. Make your way to the south oval and keep walking directly due south. Collings Hall will be the fourth building on your right.',
	'collums_commissary': 'Walk past Crossroads and out the southern exit. Make your way to the south oval and keep walking directly due south until you reach Lindsey street. When you hit Lindsey Street, turn left and walk directly due east. Once you cross Jenkins avenue, the Collums Commissary will be the second building on your left.',
	'copeland_hall': 'Walk past Crossroads and out the southern exit. Make your way to the south oval and keep walking directly due south. Copeland Hall will be the fifth building on your right.',
	'couch_cafeteria': 'Walk past Crossroads and out the southern exit. Make your way to the south oval and keep walking directly due south, even past Lindsey street. Past the three dorms, you\'ll run into a circular shaped building. That will be the Couch Cafeteria.',
	# 'couch_center': '',
	# 'cross_center': '',
	# 'dale_hall': '',
	# 'dale_hall_tower': '',
	# 'devon_energy_hall': '',
	# 'dunham_residential_college': '',
	# 'ellison_hall': '',
	# 'elm_ave_parking_facility': '',
	# 'engineering_laboratory': '',
	# 'evans_hall': '',
	# 'exxon_mobile_lawrence_g_rawl_practice_facility': '',
	# 'facilities_management_complex': '',
	# 'farzaneh_hall': '',
	# 'fears_structural_engineering_lab': '',
	# 'felgar_hall': '',
	# 'fine_arts_center': '',
	# 'five_partners_place': '',
	# 'forum_building': '',
	# 'four_partners_place': '',
	# 'fred_jones_junior_memorial_art_center': '',
	# 'gaylord_hall': '',
	# 'the_gaylord_family_oklahoma_memorial_stadium': '',
	'george_lynn_cross_hall': 'Walk past Crossroads and out the southern exit. Make your way to the south oval and keep walking directly due south until you can make a left on the second building down.',
	# 'goddard_health_center': '',
	# 'gould_hall': '',
	# 'headington_hall': '',
	# 'headington_residential_college': '',
	# 'housing_offices': '',
	# 'human_resources': '',
	# 'jacobs_field': '',
	# 'jacobson_hall': '',
	# 'jenkins_avenue_parking_facility': '',
	# 'jimmie_austin_o_u_golf_course': '',
	'jim_thorpe_multi_cultural_center': 'Walk past Crossroads and out the southern exit. Make your way to the south oval and keep walking directly due south, even past Lindsey street. Past the three dorms, you\'ll eventually run into a 3 pointed star shaped building. The Jim Thorpe Multi-Cultural Center, also known as the Commons Restaurant, will be located on the north west side of the block.',
	# 'kaufman_hall': '',
	# 'kraettli_apartments': '',
	# 'lissa_and_cy_wagner_student_academic_services_center': '',
	# 'lloyd_noble_center': '',
	# 'l_dale_mitchell_baseball_park': '',
	# 'mccarter_hall': '',
	# 'michael_f_price_college_of_business': '',
	# 'monnet_hall': '',
	# 'mosier_indoor_athletic_facility': '',
	# 'national_weather_center': '',
	# 'newman_hall': '',
	# 'nielsen_hall': '',
	# 'norman_fire_department_number_3': '',
	# 'nuclear_engineering_laboratory': '',
	# 'observatory': '',
	# 'old_faculty_club': '',
	# 'one_partners_place': '',
	# 'o_u_police_department': '',
	# 'o_u_traditions_square_east': '',
	# 'o_u_traditions_square_west': '',
	# 'parking_services': '',
	# 'physical_sciences_center': '',
	# 'reynolds_performing_arts_center': '',
	# 'richards_hall': '',
	# 'robertson_hall': '',
	# 'rupel_j_jones_theatre': '',
	# 'sam_noble_oklahoma_museum_of_natural_history': '',
	# 'sarkeys_energy_center': '',
	# 'sarkeys_physical_fitness_center': '',
	# 'science_hall': '',
	# 'sells_swim_complex': '',
	# 'sooner_cottage_suites': '',
	# 'stephenson_life_sciences_research_center': '',
	# 'stephenson_research_and_technology_center': '',
	# 'sutton_hall': '',
	# 't_howard_mccasland_field_house': '',
	# 'theta_m_dempsey_transportation_operations_center': '',
	# 'three_partners_place': '',
	# 'two_partners_place': '',
	# 'university_book_exchange': '',
	# 'university_of_oklahoma_foundation': '',
	# 'viersen_gymnastics_center': '',
	# 'walker_tower': '',
	# 'whitehand_hall': ''
}
