union_room_directions = {'kxou': 'Its the glass room in front of you to the left!',
                         'post_office': 'It\'s on the right side of the hallway towards crossroads, across from the Starbucks. ',
                         'sooner_card': 'It\'s on the left side of the hallway leading towards crossroads, to the left of the Starbucks.',
                         'ou_passport': 'It\'s on the left side of the hallway leading towards crossroads, to the left of the Starbucks.',
                         'student_art_gallery': 'It\'s on the left side of the hallway leading towards crossroads, to the left of the Starbucks.',
                         'starbucks': 'It\'s in the hallway between Crossroads and the center of the union.',
                         'credit_union': 'Go down the hall to your left towards Crossroads. It will be on your left at the bottom of the ramp.',
                         'crossroads': 'From the center of the union, go down the hall to your left. It will be on your right after the ramp.',
                         'lgbtq_lounge': 'From crossroads, the L. G. B. T. Q. lounge is down the hallway to the left of the counter, past all of the chairs. It\'s behind the glass door to your right.',
                         'sooner_room': 'From crossroads, the sooner room is to the left, past the microwave, at the end of the hallway just past the bathrooms.',
                         'student_government_association': 'Go down the hall to your left. Turn right after going down the ramp. Its at the end of the hallway on the right.',
                         'one_university_store': 'The One U. Store is the glass room in the center of the union, across from the union market.',
                         'union_market': "The Union Market is the room with two cash registers across from the One U. Store, between the food court and the center of the union.",
                         'will_rogers_room': 'The Will Rogers Room is across from the food court, on the north side of the union.',
                         'food_court': 'The food court is on the north side of union, past the One U. Store and on your right.',
                         'clarke_anderson_room': 'The Clarke-Anderson Room, also called the Schooner Room, is on the northwest part of the union. It\' past the Will Rogers Room with all the chairs.',
                         'stuart_landing': 'The Stuart Landing is immediately in front of the central staircase, on the second floor. It\'s next to the Beaird Lounge.',
                         'alma_wilson_room': "The Alma Wilson room is on the second floor, in the hallway between Meacham Auditorium and the central staircase. The Alma Wilson room is closest to the staircase, across from the elevator.",
                         'pioneer_room': "The Pioneer room is on the second floor, in the hallway between Meacham Auditorium and the central staircase. It's to the left of the elevator, across from the Alma Wilson Room.",
                         'david_f_schrage_traditions_room': "The Traditions Room is on the second floor, in the hallway between Meacham Auditorium and the central staircase. It's to the left of the elevator, across from the John and Louise Houchin Rooms.",
                         'john_houchin_room': "The Traditions Room is on the second floor, in the hallway between Meacham Auditorium and the central staircase. It's in the middle of the hallway, across from the Traditions Room.",
                         'louise_houchin_room': "The Traditions Room is on the second floor, in the hallway between Meacham Auditorium and the central staircase. It's in the middle of the hallway, across from the Traditions Room.",
                         'david_l_boren_lounge': "The Boren Lounge is just to the north of Meacham Auditorium. It's the open room across from the Presidents Room, with all of the bookcases.",
                         'presidents_room': "The Presidents Room is on the second floor, in the hallway between Meacham Auditorium and the central staircase. It's across from the Boren Lounge, and has two entrances.",
# TODO: Fine tune the directions below this line.
                         'meacham_auditorium':'The Meacham Auditorium is on the second floor, in the lobby beside the gender equality center.',
                         'volunteer_office': 'The Volunteer Office is on the second floor, in the hallway in front of the Student Affairs office and the staircase.',
                         'student_affairs': 'Student Affairs is on the second floor. It is at the end of the hallway by bathrooms and the staircase leading up from Crossroads. ',
                         'conoco_student_leadership_wing': 'The Student Leadership Wing is on the second floor.',
                         'beaird_lounge': 'The Beaird Lounge is on the second floor, in the large room between the Frontier Room and Stuart Landing',
                         'flint_study_center_computer_lab': 'The Flint Study Center Computer Lab is in the large room beside Stuart Landing. It is in the hallway beside the Crimson Meeting Room.',
                         'crimson_meeting_room': 'The Crimson Meeting Room is on the second floor. It is in the large room beside Stuart Landing. It is in a hallway jsut beside the stairs.',
                         'bartlet_study_room': 'The Bartlet Study Room is on the second floor. It is just inside the large room beside Stuart Landing.',
                         'frontier_room': 'The Frontier Room is on the second floor. It is between the large room by Stuart Landing and the Heritage room, just up the stairs.',
                         'weitzenhoffer_dining_room': 'The Weitzenhoffer Dining Room is on the second floor between the Frontier Room and the Heritage room.',
                         'heritage_room': 'The Heritage Room is on the second floor. It is at the end of the hallway in front of the Jan Marie and Richard L. Crawford University Club.',
                         'crawford_university_club': 'The Crawford University Club is the second floor. It is up the stairs in the hallway just beyond the Beaird Lounge.',
                         'career_services': 'Career Services is on the third floor. It is up the central staircase on the opposite side of the Molly Shi Boren Ballroom',
                         'molly_shi_boren_ballroom': 'The Molly Shi Boren Ballroom is on the third floor. It is the large room beside the central staircase',
                         'governors_room': 'The Governors Room is on the third floor just past the Molly Shi Boren Ballroom',
                         'regents_room': 'The Regents Room is on the third floor between the Governors Room and the Associates Room.',
                         'associates_room': 'The Associates Room is on the third floor. It is past the Molly Shi Boren Ballroom at the very end of the hallway past the Governors Room',
                         'scholars_room': 'The Scholars Room is on the third floor. It is past the Molly Shi Boren Ballroom in the lobby just beyond the restrooms.',
                         'meacham_balcony': 'The Meacham Balcony is on the third floor. It is up the stairs to the left of Meacham Auditorium.',
                         'student_life': 'Student Life is on the third floor. It is up stairs leading from Crossroads, just past the bathrooms by the stairs.',
                         # 'student_leadership_wing': 'Go down the hallway to your left then turn right after the ramp. Use the stairs on your left to get to the third floor. Go through the student life hallway on your left. ', # isn't this one redundant?
                         'union_administration_and_programming_board': 'The Union Administration and Programming Board is on the third floor on the opposite side of the Paul Massad Conference Room using the central staircase.',
                         'alumni_association': 'The Alumni Association is on the fourth floor on the opposite side the Paul Massad Conference Room using the central staircase.',
                         'paul_massad_conference_room': 'The Paul Massad Conference Room is on the fourth floor using the central staircase. Facing the staircase, it is immedietly to the left.'}
