union_room_directions = {'kxou': 'Its the glass room in front of you to the left!',
                         'post_office': 'It\'s on the right side of the hallway towards crossroads, across from the Starbucks. ',
                         'sooner_card': 'It\'s on the left side of the hallway leading towards crossroads, to the left of the Starbucks.',
                         'ou_passport': 'It\'s on the left side of the hallway leading towards crossroads, to the left of the Starbucks.',
                         'student_art_gallery': 'It\'s on the left side of the hallway leading towards crossroads, to the left of the Starbucks.',
                         'starbucks': 'It\'s in the hallway between Crossroads and the center of the union.',
                         'credit_union': 'Go down the hall to your left towards Crossroads. It will be on your left at the bottom of the ramp.',
                         'crossroads': 'From the center of the union, go down the hall to your left. It will be on your right after the ramp.',
                         'lgbtq_lounge': 'From crossroads, the L. G. B. T. Q. lounge is down the hallway to the left of the counter, past all of the chairs. It\'s behind the glass door to your right.',
                         'sooner_room': 'From crossroads, the sooner room is to the left, past the microwave, at the end of the hallway just past the bathrooms.',
                         'student_government_association': 'Go down the hall to your left. Turn right after going down the ramp. Its at the end of the hallway on the right.',
                         'one_university_store': 'The One U. Store is the glass room in the center of the union, across from the union market.',
                         'union_market': "The Union Market is the room with two cash registers across from the One U. Store, between the food court and the center of the union.",
                         'will_rogers_room': 'The Will Rogers Room is across from the food court, on the north side of the union.',
                         'food_court': 'The food court is on the north side of union, past the One U. Store and on your right.',
                         'clarke_anderson_room': 'The Clarke-Anderson Room, also called the Schooner Room, is on the northwest part of the union. It\' past the Will Rogers Room with all the chairs.',
                         'stuart_landing': 'The Stuart Landing is immediately in front of the central staircase, on the second floor. It\'s next to the Beaird Lounge.',
                         'alma_wilson_room': "The Alma Wilson room is on the second floor, in the hallway between Meacham Auditorium and the central staircase. The Alma Wilson room is closest to the staircase, across from the elevator.",
                         'pioneer_room': "The Pioneer room is on the second floor, in the hallway between Meacham Auditorium and the central staircase. It's to the left of the elevator, across from the Alma Wilson Room.",
                         'david_f_schrage_traditions_room': "The Traditions Room is on the second floor, in the hallway between Meacham Auditorium and the central staircase. It's to the left of the elevator, across from the John and Louise Houchin Rooms.",
                         'john_houchin_room': "The Traditions Room is on the second floor, in the hallway between Meacham Auditorium and the central staircase. It's in the middle of the hallway, across from the Traditions Room.",
                         'louise_houchin_room': "The Traditions Room is on the second floor, in the hallway between Meacham Auditorium and the central staircase. It's in the middle of the hallway, across from the Traditions Room.",
                         'david_l_boren_lounge': "The Boren Lounge is just to the north of Meacham Auditorium. It's the open room across from the Presidents Room, with all of the bookcases.",
                         'presidents_room': "The Presidents Room is on the second floor, in the hallway between Meacham Auditorium and the central staircase. It's across from the Boren Lounge, and has two entrances.",
# TODO: update below this line
                         'meacham_auditorium': 'Turn around and use the stairs to go up to the second floor. Then turn left. Its on the right side of the atrium at the end of the hall.',
                         'volunteer_office': 'Turn around and use the stairs to go up to the second floor. Then turn left. Its at the end of the hallway down the short flight of stairs.',
                         'student_affairs': 'Turn around and use the stairs to go up to the second floor. Then turn left. Go all the way down the hallway and down the short flight of stairs. It will be at the end of the hallway on your right.',
                         'conoco_student_leadership_wing': 'Turn around and use the stairs to go up to the second floor. Then turn left. Go all the way down the hallway and down the short flight of stairs. It will be on the right side of the hallway on your right.',
                         'beaird_lounge': 'Turn around and use the stairs to go up to the second floor. Then turn right. It will be the room on your right after the double doors.',
                         'flint_study_center_computer_lab': 'Turn around and use the stairs to go up to the second floor. Then turn right. Its on your left after the double doors. ',
                         'crimson_meeting_room': 'Turn around and use the stairs to go up to the second floor. Then turn right. Its on your left after the double doors. ',
                         'bartlet_study_room': 'Turn around and use the stairs to go up to the second floor. Then turn right. Its on your left after the double doors. ',
                         'frontier_room': 'Turn around and use the stairs to go up to the second floor. Then turn right. Its the first room on your left after the short flight of stairs. ',
                         'weitzenhoffer_dining_room': 'Turn around and use the stairs to go up to the second floor. Then turn right. Its the second room on your left after the short flight of stairs. ',
                         'heritage_room': 'Turn around and use the stairs to go up to the second floor. Then turn right. Its the third room on your left after the short flight of stairs. ',
                         'crawford_university_club': 'Turn around and use the stairs to go up to the second floor. Then turn right. Its the big room on your right after the short flight of stairs. ',
                         'career_services': 'Turn around and use the stairs to go up to the third floor. It will be the room on your left.',
                         'molly_shi_boren_ballroom': 'Turn around and use the stairs to go up to the third floor. Then turn right. It will be the room on your right. ',
                         'governors_room': 'Turn around and use the stairs to go up to the third floor. Then turn right. It will be the first room on your right after the ballroom. ',
                         'regents_room': 'Turn around and use the stairs to go up to the third floor. Then turn right. It will be the second room on your right after the ballroom. ',
                         'associates_room': 'Turn around and use the stairs to go up to the third floor. Then turn right. It will be the third room on your right after the ballroom. ',
                         'scholars_room': 'Turn around and use the stairs to go up to the third floor. Then turn right. It will be the room in the corner on your left after the ballroom. ',
                         'meacham_balcony': 'Go down the hallway to your left then turn right after the ramp. Use the stairs on your left to get to the third floor. It will be at the end of the hallway to your right after a short flight of stairs. ',
                         'student_life': 'Go down the hallway to your left then turn right after the ramp. Use the stairs on your left to get to the third floor. It will be on your left.',
                         # 'student_leadership_wing': 'Go down the hallway to your left then turn right after the ramp. Use the stairs on your left to get to the third floor. Go through the student life hallway on your left. ', # isn't this one redundant?
                         'union_administration_and_programming_board': 'Turn around and use the stairs to go up to the fourth floor. Then turn left. It will be the first room on your right.',
                         'alumni_association': 'Turn around and use the stairs to go up to the fourth floor. Then turn left. It will be the first room on your left.',
                         'paul_massad_conference_room': 'Turn around and use the stairs to go up to the fourth floor. It will be the room in front of you to the right. '}
